### ISSUE TITLE
Need to generate JPG with proper format

### ISSUE THREAD

**Issue by daparix** [Thrilleratplay/bootsplash-coreboot#2]
Looking at your jpg, it shows "progressive".
When exporting from GIMP, do:
- check "advanced options"
- untick "progressive"
- select "4:2:0 (Chroma quartered)"

This should make your bootsplash image visible

**Comment by Thrilleratplay** [comment]
Thank you.  I appreciate the instructions but I was able to do get it to work a few months ago using the steps from the Purism blog post and added the results to [Thrilleratplay/coreboot-builder-scripts](https://github.com/Thrilleratplay/coreboot-builder-scripts).  I should have updated the README in this repo.  I apologize for not doing so.
